#
# Copyright (C) 2024 Wind River Systems, Inc.
#

# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "wr-amd-versal"
BBFILE_PATTERN_wr-amd-versal := "^${LAYERDIR}/"
BBFILE_PRIORITY_wr-amd-versal = "7"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_wr-amd-versal = "1"

LAYERDEPENDS_wr-amd-versal = "core wrlinux xilinx-tools xilinx xilinx-bsp xilinx-standalone meta-arm"
LAYERSERIES_COMPAT_wr-amd-versal = "wrl scarthgap"
